### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by harry-uglow** [montrealrobotics/active-domainrand#1]
Hi there,

Thanks for releasing this source code for your recent paper. Would it be possible to add installation instructions to the README? In particular I'm having trouble finding gym_ergojr. Does this need to be added manually as a submodule?

Many thanks,
Harry

**Comment by bhairavmehta95** [comment]
Hi!

https://github.com/fgolemo/gym-ergojr will likely need to be `pip` installed if you're trying to run the ErgoJr experiments. Other than that, it should run out of the box with the commands we have in the readme.

Can you let me know what error you're getting?

**Comment by harry-uglow** [comment]
Thanks for your reply. I was running `python setup.py install` which outputs this when dealing with gym_ergojr:

```
Processing dependencies for diffsim==1.0
Searching for gym_ergojr>=1.2
Reading https://pypi.org/simple/gym_ergojr/
Reading https://pypi.org/simple/gym-ergojr/
Couldn't find index page for 'gym_ergojr' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
No local packages or working download links found for gym_ergojr>=1.2
error: Could not find suitable distribution for Requirement.parse('gym_ergojr>=1.2')
```

However using `pip install git+https://github.com/fgolemo/gym-ergojr` and then `python setup.py install` works just fine. Thanks for your help.
