### ISSUE TITLE
missing scripts

### ISSUE THREAD

**Issue by dcharrezt** [montrealrobotics/active-domainrand#2]
Hello,

Thanks for uploading the code for your paper, in [README](https://github.com/montrealrobotics/active-domainrand/tree/master/scripts) _multiseed.sh_ and with _seed.sh_ are described, It would be helpful if you can upload them.

I am also getting this error when I try to run the experiments

```
    from common.envs.randomized_vecenv import make_vec_envs
  File "/******/active-domainrand/common/envs/randomized_vecenv.py", line 6, in <module>
    from baselines.common.vec_env import VecEnv, CloudpickleWrapper
ModuleNotFoundError: No module named 'baselines'
```

**Comment by bhairavmehta95** [comment]
You'll need to install `baselines` from OpenAI.

Unfortunately, that `multiseed.sh` and `seed.sh` were internal dev tools, and likely won't be useful outside of our cluster setup. Will remove the reference.
