### ISSUE TITLE
Randomization ranges mismatch for ergoreacher

### ISSUE THREAD

**Issue by SharathRaparthy** [montrealrobotics/active-domainrand#3]
The randomization ranges of `Ergo-Reacher` environment (`common/envs/config/ErgoReacherRandomized/*.json`) are not matching with the ranges that are mentioned in the paper (Appendix F, Table 1). Could you please change?

**Comment by bhairavmehta95** [comment]
Please use the ones in the repo. The paper seems to have some old parameters.
